### ISSUE TITLE
Concurrency issue with Java code on P2W 0.9-RC2

### ISSUE THREAD

**Issue by vasiliyz** [play2war/play2-war-plugin#136]
I tried to package a sample play app (2.1-RC1, 2.1.0) with war plugin (0.9-RC1, 0.9-RC2) on some servers (tomcat6,tomcat7) with servlet version (2.5,3.0) and found that my play 2 application can handle only one (!) request per moment. When i had put a complex work or just Tread.sleep(10000) into any controller than all other request to other controllers are waited. It makes impossible to use war packaging in prod environment. Its my fault with app configuration or the expected behavior of war packaging ?

**Comment by dlecan** [comment]
> the expected behavior of war packaging

Surely not :) That's why Play2war 0.9 series is still in beta/RC cycle.

Performances tests were made on 0.8 series (so for Play 2.0.4) and they were OK.

Internal Play 2.1 API has major improvements due to Scala 2.10 and so Play2war 0.9 may have code adaptation issues.

Thanks for reporting that important issue, I can reproduce it.

**Comment by dlecan** [comment]
This issue cannot be reproduced on v0.7.4, v0.8.1 or v0.8.2-SNAPSHOT (for Play 2.0.x).

Only 0.9 series is affected (so for Play 2.1.x).

**Comment by dlecan** [comment]
This issue doesn't occur with Scala code.
Only Java code has a concurrent execution issue.
