### ISSUE TITLE
Can't Deploy to Web Logic 12c

### ISSUE THREAD

**Issue by kevinmeredith** [play2war/play2-war-plugin#203]
Hi -

I tried to deploy my play2war-generated WAR to Web Logic 12c with both Servlet 2.5 and 3 versions, but neither worked.

I kept seeing this type of error message in Web Logic:

<Nov 26, 2013 2:24:27 PM EST> <Error> <Weblogic-Validation> <BEA-2156404> <Unable to find a Validation Context. java.lang.RuntimeException: javax.naming.NamingException: String ind
ex out of range: -1

Any ideas on how to deploy the WAR in Web Logic?

Thank you,
Kevin

**Comment by kevinmeredith** [comment]
respectful bump - this plug-in was easy to set up and deploy on Tomcat for me

**Comment by dlecan** [comment]
Weblogic  is not supported by Play2War. It needs many specific configuration.
If you need Weblogic compatibility, you will have to do it yourself :)

Begin to increase logging.

**Comment by kevinmeredith** [comment]
Thanks for letting me know, @dlecan!

**Comment by dlecan** [comment]
If you have more information, do not hesitate to reopen this issue.

**Comment by tomzx** [comment]
@kevinmeredith I assume you haven't gone any further into this?
- If you did, how far did you get?
- If not, what did you ended up going with instead?

I'm currently trying to migrate a project from 10.3 (working with play2war and play 2.1.3) to 12.1 (tried latest play2war and play 2.3.8).

Thanks for the information, it'll be appreciated.

**Comment by cecton** [comment]
Hello,

Well if that's easy enough for a beginner in Scala to fix, maybe I can help.

I'm running Weblogic 12c (running on Docker), play 2.3.9, java 7, servlet 2.5 (works on tomcat, servlet 3.0 didn't work on tomcat 7 for some reason but I suspect bad luck), play2-war-plugin 1.3-beta3. 

I found these 2 log files that reflect what I have in the stdout:

[weblogic:/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/logs/AdminServer.log](https://gist.github.com/6b78d98a2f957270e50b23d869b49182)
[weblogic:/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/logs/base_domain.log](https://gist.github.com/b2d3c7a2a5cdba16cbee0398000f1bd6)

Then the stdout keep repeating this in loop:

```
<Jul 6, 2016 8:38:52 AM UTC> <Error> <Kernel> <BEA-000802> <ExecuteRequest failed
 java.lang.StackOverflowError.
java.lang.StackOverflowError
        at org.slf4j.impl.JDK14LoggerFactory.getLogger(JDK14LoggerFactory.java:67)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:242)
        at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:204)
        at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:291)
        at java.util.logging.Logger.log(Logger.java:616)
        Truncated. see log file for complete stacktrace
>
```

(The whole weblogic application is not usable at this point but no CPU consumption)

**Comment by tomzx** [comment]
@cecton You might be interested in https://github.com/tomzx/play-framework-notes/tree/12.1. I compiled a bunch of notes while I was working on getting weblogic 12 to work and it appears the issue you are having is related to [this](https://github.com/tomzx/play-framework-notes/tree/12.1#warweb-infweblogicxml), where you need to override the logger used so weblogic uses the one that comes with play and not weblogic itself.

**Comment by cecton** [comment]
@tomzx many thanks! Adding the weblogic.xml helps weblogic to not get stuck in an infinite loop. But it still not works because of some other issue.

First of all, I must say I don't expect you to help me too much on this one but if any idea comes to your mind about this new issue, it would be very welcome.

(Btw, I realized that there is an extension for [redirecting the logger or something](https://github.com/play2war/redirect-playlogger). Maybe that could help too instead of disabling it completely. I don't know.)

Now I can actually curl the URL and receive 200 (something I shouldn't have) and see in weblogic's stdout (when I curl):

```
[error] play - Play server as not been initialized. Due to a previous error ?
```

The full logs are located [here](https://gist.github.com/0882e365fae5e899f6df5be9425f9acb).

And I suspect this error to be the main reason that it doesn't work:

```
[info] play - Force Play 'application.context' to '/myproject-1.0-SNAPSHOT/'
<Jul 7, 2016 11:26:23 AM UTC> <Warning> <HTTP> <BEA-101162> <User defined listener play.core.server.servlet25.Play2Servlet failed: java.lang.IllegalArgumentException: Cannot check isDirectory for a URL with protocol='zip'.
java.lang.IllegalArgumentException: Cannot check isDirectory for a URL with protocol='zip'
        at play.utils.Resources$.isDirectory(Resources.scala:18)
        at play.api.i18n.DefaultMessagesPlugin$$anonfun$loadMessages$1.apply(Messages.scala:351)
        at play.api.i18n.DefaultMessagesPlugin$$anonfun$loadMessages$1.apply(Messages.scala:351)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
        at scala.collection.immutable.List.foreach(List.scala:381)
        Truncated. see log file for complete stacktrace
```

I found that there is something a bit similar for JBoss7 [here](https://github.com/play2war/play2-war-plugin/wiki/Configurationspecialebeanjboss7).

Also, I switched to servlet 3.0 because your notes mention it, the result is similar yet different. The curl request doesn't return anything (it gets stuck, nothing on the stdout of weblogic).

The full logs are located [here](https://gist.github.com/644917adcd1a5183f6c5cd7b94eb5a2e). Many errors like the `String index out of range: -1` have disappeared.

But the final message is very similar:

```
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
<Jul 7, 2016 11:52:51 AM UTC> <Warning> <HTTP> <BEA-101162> <User defined listener play.core.server.servlet30.Play2Servlet failed: java.lang.IllegalArgumentException: Cannot check isDirectory for a URL with protocol='zip'.
java.lang.IllegalArgumentException: Cannot check isDirectory for a URL with protocol='zip'
        at play.utils.Resources$.isDirectory(Resources.scala:18)
        at play.api.i18n.DefaultMessagesPlugin$$anonfun$loadMessages$1.apply(Messages.scala:351)
        at play.api.i18n.DefaultMessagesPlugin$$anonfun$loadMessages$1.apply(Messages.scala:351)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
        at scala.collection.immutable.List.foreach(List.scala:381)
        Truncated. see log file for complete stacktrace
> 
```

I checked the BEA code:

> BEA-101162: User defined listener {0} failed: {1}.
>    Cause: The listener failed while processing the event fired by the container.
>    Action: Check the exception for the exact error message and fix the listener code.
> 
>    Level: 1
> 
>    Type: WARNING
> 
>    Impact: HTTP
> (from [here](https://docs.oracle.com/html/E26117_01/chapter_bea_messages.htm))

The good thing also is that I can recognize some logs coming from my application.

**Comment by cecton** [comment]
After a small research in the code of playframework. It seems they handle jar and zip in the recent version. But not in the 2.3.9 (which I need because I have to make it to run on java7), they only handle jar... which should be the same.

https://github.com/playframework/playframework/blob/2.3.9/framework/src/play/src/main/scala/play/utils/Resources.scala

Update: It seems the change is already in the 2.3.x branch. I suppose they will release a 2.3.11 with it.

**Comment by tomzx** [comment]
@cecton As I noted in my notes, I only tested for play 2.1.3. If I remember correctly, I had attempted to make a latest version of play to work at the time, but I had some issues, and since my task was to make our current website running with the least amount of changes, not upgrading play was part of that.

I do recall seeing the error you describe (`java.lang.IllegalArgumentException: Cannot check isDirectory for a URL with protocol='zip'`), however I don't remember if/how I dealt with that (I most likely didn't have to deal with it using play 2.1.3). If you are able to try running an old version of play and you're fine with that, then I suggest you give that a try.

**Comment by cecton** [comment]
@tomzx I have made a Docker image with Play framework 2.3.x running and able to run on Weblogic 12c [here](https://github.com/cecton/playframework-for-weblogic12c) (Docker image: [cecton/playframework-for-weblogic12c](https://hub.docker.com/r/cecton/playframework-for-weblogic12c/)). 

If someone else runs to this post and need to get Play working on Weblogic 12c, I suggest to use this Docker image and the plugin play2war with following configuration:

build.sbt:

```
Play2WarKeys.servletVersion := "3.0"
```

project/plugins.sbt:

```
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.3-beta3")
```

You will also need to do [this](https://github.com/tomzx/play-framework-notes/tree/12.1#warweb-infweblogicxml).

And use the notes of @tomzx located [here](https://github.com/tomzx/play-framework-notes/tree/12.1) if you encounter any issue.
