### ISSUE TITLE
Play2War application on tomcat starts a thread local and fails to remove it

### ISSUE THREAD

**Issue by erkinun** [play2war/play2-war-plugin#207]
Dec 15, 2013 3:13:48 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/appName] created a ThreadLocal with key of type [scala.concurrent.stm.ccstm.InTxnImpl$](value [scala.concurrent.stm.ccstm.InTxnImpl$@4f4c8e7d]) and a value of type [scala.concurrent.stm.ccstm.InTxnImpl](value [InTxnImpl@2345c7ee%28Detached, slot=-1, subsumptionAllowed=true, priority=0, readCount=0, bargeCount=0, writeCount=0, readVersion=0x0, cumulativeBlockingNanos=0, commitBarrier=null%29]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

We are having this issue for about one month but the application was in production since June 2013. 

Right now our configuraton is: 

Play : 2.1.3
play2War : 0.9
Java : 1.6

**Comment by dlecan** [comment]
Please, look at #108, #171, #161 and especially [this comment](https://github.com/dlecan/play2-war-plugin/issues/161#issuecomment-19216126).

Without more information, it's an Akka/Play issue.

**Comment by erkinun** [comment]
Thank you for the info. So what is the suggested course of action given this scenario? Does it only effect the shutdown process or it also leaks from the heap memory as well?

**Comment by dlecan** [comment]
This issue has never been reported as a "real" memory leak. When Tomcat shutdowns the container, it considers remaining running threads/threadlocals as potential memory leaks because they are not stopped by the application and it has to stop them itself.
Akka runs like this, and it shouldn't be a problem for a running application.

However, after many hot redeployment (without Tomcat restart), this may lead to problems.

**Comment by btgrant-76** [comment]
I realize this is an old issue and I've found plenty of references that this is _not_ a play2war issue (I agree). We've been troubleshooting some memory with our container-deployed Play 2 app that have necessitated server restarts a couple of times per week. I consulted with members of another team using Play 2 and play2war and they recommended adding `play.akka.daemonic=on` to `application.conf` and, at least based on initial testing, our memory issues are gone. I'll know more once we take the changes live, but we can no longer reproduce the memory growth in our QA environment.

See also:  http://stackoverflow.com/questions/25443351/play-war-deployment-prevents-tomcat-to-stop

**Comment by dlecan** [comment]
@btgrant-76 thank you for the feedback. If you can confirm this workaround, I'll add it in P2W documentation.

**Comment by btgrant-76** [comment]
I may have spoken too soon. We took this config change live last week and we're still seeing the memory leak. Since I need to do some additional testing to figure out what's wrong, I'll post any details that I find if there's any coloration between the config change, but that seems unlikely at this point.
