### ISSUE TITLE
Question regading Production version of Play2war

### ISSUE THREAD

**Issue by ritu-p** [play2war/play2-war-plugin#246]
Hi,
We are currently using Play2War for war file generation.My organization has speculations since the play2war version now we use is a beta version,whether there will be a production level release of Play2war in near future.

**Comment by dlecan** [comment]
It used to have stable versions for Play 2.0 and 2.1 series.
For Play 2.2, it's a bit longer because I have less time to work on Play2War, but @yanns provides me a lot of help.
Play2war 1.2.x series is flagged "beta" but very few bugs have been reported.

Finally, Play2War is not the future of Play, but more something to help your ops to accept Play. In the future, you should convinced them to use native Play deployment model (official support, more features, more performances ...)

**Comment by ritu-p** [comment]
Thanks Damien.
I will convey this to my senior management.
